# Generated by Django 5.2.14 on 2026-05-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supplier',
            new_name='suppliers_s_tax_id_b5d5af_idx',
            old_name='suppliers_su_tax_id_32224c_idx',
        ),
        migrations.RenameIndex(
            model_name='supplier',
            new_name='suppliers_s_status_e60785_idx',
            old_name='suppliers_su_status_56e639_idx',
        ),
        migrations.RenameIndex(
            model_name='supplier',
            new_name='suppliers_s_city_2bfba9_idx',
            old_name='suppliers_su_city_264195_idx',
        ),
    ]
