# Generated by Django 5.2.14 on 2026-05-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supplierdocument',
            new_name='documents_s_supplie_8ef247_idx',
            old_name='documents_s_supplier_1e5069_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierdocument',
            new_name='documents_s_status_431378_idx',
            old_name='documents_s_status_10ba50_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierdocument',
            new_name='documents_s_expires_0cc00c_idx',
            old_name='documents_s_expires_ee8dd0_idx',
        ),
    ]
